name: Test changed-files

on:
  push:
    branches:
      - main
  worflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Get Latest
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: actions/checkout@v3

      - id: files
        uses: tj-actions/changed-files@v37
        with:
          json: true
          write_output_files: true
      
      - id: catjson
        run: |
          cat .github/outputs/all_changed_files.json
